# Generated by Django 5.2.8 on 2025-11-08 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=170)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cancelado', 'Cancelado')], default='borrador', max_length=15)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('banner_url', models.URLField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='accounts.cuenta')),
            ],
            options={
                'ordering': ('-creado_en',),
                'unique_together': {('cuenta', 'slug')},
            },
        ),
    ]
