# Generated by Django 5.2.8 on 2025-11-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
