# Generated by Django 5.2.8 on 2025-11-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_evento_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='banner_url',
        ),
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
    ]
