# Generated by Django 5.2.8 on 2025-11-13 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellido1', models.CharField(max_length=150, verbose_name='Apellido paterno')),
                ('apellido2', models.CharField(blank=True, max_length=150, verbose_name='Apellido materno')),
                ('telefono_movil', models.CharField(max_length=30)),
                ('pais', models.CharField(default='CL', max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('recibe_novedades', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
