# Generated by Django 5.2.8 on 2025-11-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('access_policy', models.CharField(choices=[('un_dia', 'Un día'), ('todos_los_dias', 'Todos los días')], default='un_dia', max_length=20)),
                ('reentry_rule', models.CharField(choices=[('ilimitado', 'Ilimitado'), ('una_vez_por_dia', 'Una vez por día')], default='una_vez_por_dia', max_length=20)),
                ('includes_congress', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('valid_day', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='events.evento')),
            ],
            options={
                'ordering': ('-creado_en',),
                'unique_together': {('evento', 'nombre')},
            },
        ),
    ]
