# Generated by Django 5.2.8 on 2025-11-11 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_email_and_more'),
        ('events', '0001_initial'),
        ('tickets', '0002_tipoticket_is_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('monto_descuento', models.PositiveIntegerField()),
                ('usos_maximos', models.PositiveIntegerField(default=1)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='accounts.cuenta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='events.evento')),
                ('tipo_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='tickets.tipoticket')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
