# Generated by Django 5.2.8 on 2025-11-08 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_email_and_more'),
        ('events', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='accounts.cuenta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='events.evento')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=36, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('quemado', 'Quemado')], default='disponible', max_length=12)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('asistente_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.evento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.orden')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tipoticket')),
            ],
        ),
    ]
