# Generated by Django 5.2.8 on 2025-11-12 19:52

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_email_and_more'),
        ('events', '0001_initial'),
        ('orders', '0004_ticket_replaced_by_alter_ticket_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Monto fijo')], max_length=10)),
                ('valor', models.PositiveIntegerField(help_text='Porcentaje o monto fijo en CLP según tipo.')),
                ('usos_maximos', models.PositiveIntegerField(default=1)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('valido_desde', models.DateField(blank=True, null=True)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='accounts.cuenta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='events.evento')),
            ],
        ),
        migrations.CreateModel(
            name='SharedPurchaseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=orders.models.generate_shared_code, max_length=36, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.evento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_codes', to='orders.orden')),
            ],
        ),
    ]
